# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36c490362f335214b081b27c5ca0f2e4267547097a0169e4adc23333ce3066b39b1e6a823bd1c8d5656c5397ecb1915772bf2579ef502f450db7ff0a479458eb

test:
  secret_key_base: 018a9bf4ec0490e4113eb34297bd04d76eb58c99d1222438945cfeeeec0ffb4c44737c4a1e4d3ff9fc0f06192f16c30366b9f093015622bc4e6cfef4e859f0c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
